# Generated by Django 3.2.19 on 2024-06-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
