# Generated by Django 3.2.19 on 2024-06-30 04:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
